import { z } from 'zod';

export * from './products.js';
export * from './warehouses.js';
export * from './inventory.js';
export * from './adjustments.js';
export * from './transfers.js';
export * from './stock-counts.js';
export * from './suppliers.js';
export * from './purchase-orders.js';
export * from './goods-receipts.js';
export * from './customers.js';
export * from './sales-orders.js';
export * from './reservations.js';
export * from './deliveries.js';
export * from './backorders.js';

export const emailSchema = z.string().trim().toLowerCase().email().max(254);
export const passwordSchema = z.string().min(12).max(200);
export const loginRequestSchema = z.object({ email: emailSchema, password: z.string().min(1).max(200) });
export type LoginRequest = z.infer<typeof loginRequestSchema>;

export const sessionUserSchema = z.object({
  id: z.string().uuid(),
  email: emailSchema,
  displayName: z.string().min(1).max(120),
  permissions: z.array(z.string()).readonly()
});
export type SessionUser = z.infer<typeof sessionUserSchema>;

export const brandSettingsSchema = z.object({
  displayName: z.string().trim().min(1).max(80).default('TADPODS'),
  legalName: z.string().trim().max(160).nullable().default(null),
  logoUrl: z.string().url().nullable().default(null),
  primaryColour: z.string().regex(/^#[0-9A-Fa-f]{6}$/).default('#0F766E'),
  accentColour: z.string().regex(/^#[0-9A-Fa-f]{6}$/).default('#14B8A6'),
  documentFooter: z.string().max(500).default('Generated by TADPODS')
});
export type BrandSettingsInput = z.infer<typeof brandSettingsSchema>;

export const paginationQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(25),
  search: z.string().trim().max(200).optional()
});

export const apiErrorSchema = z.object({
  statusCode: z.number().int(),
  error: z.string(),
  message: z.string(),
  requestId: z.string()
});

export const healthResponseSchema = z.object({
  status: z.literal('ok'),
  service: z.literal('TADPODS API'),
  timestamp: z.string().datetime()
});
