import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { createPdfTheme, EmailLayout } from './index.js';

describe('TADPODS document branding', () => {
  it('brands email output by default', () => {
    const html = renderToStaticMarkup(<EmailLayout title="Customer statement"><p>Account activity</p></EmailLayout>);
    expect(html).toContain('TADPODS');
    expect(html).toContain('Generated by TADPODS');
  });

  it('brands PDF metadata', () => {
    expect(createPdfTheme().metadata).toMatchObject({ creator: 'TADPODS', producer: 'TADPODS document service' });
  });
});
