import type { ReactNode } from 'react';

export type DocumentBrand = {
  displayName: string;
  legalName: string | null;
  logoUrl: string | null;
  primaryColour: string;
  accentColour: string;
  documentFooter: string;
};

export const defaultDocumentBrand: DocumentBrand = {
  displayName: 'TADPODS',
  legalName: null,
  logoUrl: null,
  primaryColour: '#0F766E',
  accentColour: '#14B8A6',
  documentFooter: 'Generated by TADPODS'
};

export function EmailLayout({
  brand = defaultDocumentBrand,
  title,
  children
}: {
  brand?: DocumentBrand;
  title: string;
  children: ReactNode;
}) {
  return (
    <html>
      <head>
        <title>{`${title} | ${brand.displayName}`}</title>
      </head>
      <body
        style={{
          margin: 0,
          background: '#f4f7f8',
          color: '#111827',
          fontFamily: 'Arial, sans-serif'
        }}
      >
        <table role="presentation" width="100%">
          <tbody>
            <tr>
              <td align="center" style={{ padding: 24 }}>
                <table
                  role="presentation"
                  width="640"
                  style={{
                    maxWidth: '100%',
                    background: '#ffffff',
                    borderRadius: 12,
                    overflow: 'hidden'
                  }}
                >
                  <tbody>
                    <tr>
                      <td
                        style={{
                          background: brand.primaryColour,
                          color: '#ffffff',
                          padding: 24,
                          fontWeight: 800,
                          fontSize: 22
                        }}
                      >
                        {brand.displayName}
                      </td>
                    </tr>
                    <tr>
                      <td style={{ padding: 28 }}>
                        <h1 style={{ marginTop: 0 }}>{title}</h1>
                        {children}
                      </td>
                    </tr>
                    <tr>
                      <td
                        style={{
                          padding: 20,
                          color: '#64748b',
                          fontSize: 12,
                          borderTop: '1px solid #dbe3ea'
                        }}
                      >
                        {brand.documentFooter}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </body>
    </html>
  );
}

export function createPdfTheme(brand: DocumentBrand = defaultDocumentBrand) {
  return {
    metadata: {
      titleSuffix: ` | ${brand.displayName}`,
      creator: brand.displayName,
      producer: 'TADPODS document service'
    },
    colours: {
      primary: brand.primaryColour,
      accent: brand.accentColour,
      text: '#111827',
      muted: '#64748B',
      border: '#DBE3EA'
    },
    header: {
      displayName: brand.displayName,
      legalName: brand.legalName,
      logoUrl: brand.logoUrl
    },
    footer: brand.documentFooter
  } as const;
}
