CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INVITED', 'SUSPENDED', 'DISABLED');
CREATE TYPE "SessionStatus" AS ENUM ('ACTIVE', 'REVOKED', 'EXPIRED');
CREATE TYPE "OutboxStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');

CREATE TABLE "User" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "email" VARCHAR(254) NOT NULL UNIQUE,
  "displayName" VARCHAR(120) NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
  "version" INTEGER NOT NULL DEFAULT 1 CHECK ("version" > 0),
  "lastLoginAt" TIMESTAMPTZ(6),
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  CONSTRAINT "User_email_lowercase" CHECK ("email" = lower("email"))
);
CREATE INDEX "User_status_email_idx" ON "User" ("status", "email");

CREATE TABLE "Role" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "key" VARCHAR(80) NOT NULL UNIQUE,
  "name" VARCHAR(120) NOT NULL UNIQUE,
  "description" VARCHAR(300),
  "system" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW()
);

CREATE TABLE "Permission" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "key" VARCHAR(120) NOT NULL UNIQUE,
  "name" VARCHAR(160) NOT NULL,
  "description" VARCHAR(300)
);

CREATE TABLE "UserRole" (
  "userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "roleId" UUID NOT NULL REFERENCES "Role"("id") ON DELETE CASCADE,
  "assignedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("userId", "roleId")
);
CREATE INDEX "UserRole_roleId_idx" ON "UserRole" ("roleId");

CREATE TABLE "RolePermission" (
  "roleId" UUID NOT NULL REFERENCES "Role"("id") ON DELETE CASCADE,
  "permissionId" UUID NOT NULL REFERENCES "Permission"("id") ON DELETE CASCADE,
  PRIMARY KEY ("roleId", "permissionId")
);
CREATE INDEX "RolePermission_permissionId_idx" ON "RolePermission" ("permissionId");

CREATE TABLE "RefreshSession" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "userId" UUID NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "tokenHash" CHAR(64) NOT NULL UNIQUE,
  "status" "SessionStatus" NOT NULL DEFAULT 'ACTIVE',
  "userAgent" VARCHAR(500),
  "ipAddress" INET,
  "expiresAt" TIMESTAMPTZ(6) NOT NULL,
  "revokedAt" TIMESTAMPTZ(6),
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "lastUsedAt" TIMESTAMPTZ(6)
);
CREATE INDEX "RefreshSession_user_status_expiry_idx" ON "RefreshSession" ("userId", "status", "expiresAt");

CREATE TABLE "AuditLog" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "userId" UUID REFERENCES "User"("id") ON DELETE SET NULL,
  "action" VARCHAR(120) NOT NULL,
  "entityType" VARCHAR(120) NOT NULL,
  "entityId" VARCHAR(120),
  "requestId" VARCHAR(120),
  "ipAddress" INET,
  "metadata" JSONB NOT NULL,
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  CONSTRAINT "AuditLog_metadata_object" CHECK (jsonb_typeof("metadata") = 'object')
);
CREATE INDEX "AuditLog_entity_idx" ON "AuditLog" ("entityType", "entityId", "createdAt");
CREATE INDEX "AuditLog_user_idx" ON "AuditLog" ("userId", "createdAt");
CREATE INDEX "AuditLog_action_idx" ON "AuditLog" ("action", "createdAt");

CREATE TABLE "IdempotencyKey" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "scope" VARCHAR(120) NOT NULL,
  "key" VARCHAR(200) NOT NULL,
  "requestHash" CHAR(64) NOT NULL,
  "responseStatus" INTEGER,
  "responseBody" JSONB,
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "expiresAt" TIMESTAMPTZ(6) NOT NULL,
  UNIQUE ("scope", "key")
);
CREATE INDEX "IdempotencyKey_expiry_idx" ON "IdempotencyKey" ("expiresAt");

CREATE TABLE "DocumentSequence" (
  "key" VARCHAR(80) PRIMARY KEY,
  "prefix" VARCHAR(20) NOT NULL CHECK (length(trim("prefix")) > 0),
  "nextValue" BIGINT NOT NULL DEFAULT 1 CHECK ("nextValue" > 0),
  "padding" INTEGER NOT NULL DEFAULT 6 CHECK ("padding" BETWEEN 1 AND 20),
  "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW()
);

CREATE TABLE "BrandSettings" (
  "singletonKey" VARCHAR(20) PRIMARY KEY DEFAULT 'default' CHECK ("singletonKey" = 'default'),
  "displayName" VARCHAR(80) NOT NULL DEFAULT 'TADPODS',
  "legalName" VARCHAR(160),
  "logoUrl" TEXT,
  "primaryColour" CHAR(7) NOT NULL DEFAULT '#0F766E' CHECK ("primaryColour" ~ '^#[0-9A-Fa-f]{6}$'),
  "accentColour" CHAR(7) NOT NULL DEFAULT '#14B8A6' CHECK ("accentColour" ~ '^#[0-9A-Fa-f]{6}$'),
  "documentFooter" VARCHAR(500) NOT NULL DEFAULT 'Generated by TADPODS',
  "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "updatedById" UUID
);

CREATE TABLE "SystemSettings" (
  "singletonKey" VARCHAR(20) PRIMARY KEY DEFAULT 'default' CHECK ("singletonKey" = 'default'),
  "defaultCurrency" CHAR(3) NOT NULL DEFAULT 'NZD' CHECK ("defaultCurrency" ~ '^[A-Z]{3}$'),
  "negativeStockEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
  "timeZone" VARCHAR(80) NOT NULL DEFAULT 'Pacific/Auckland',
  "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW()
);

CREATE TABLE "TaxRate" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "code" VARCHAR(40) NOT NULL UNIQUE,
  "name" VARCHAR(120) NOT NULL,
  "rateBasis" INTEGER NOT NULL CHECK ("rateBasis" BETWEEN 0 AND 1000000),
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW()
);

CREATE TABLE "Attachment" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "objectKey" TEXT NOT NULL UNIQUE,
  "fileName" VARCHAR(255) NOT NULL,
  "contentType" VARCHAR(160) NOT NULL,
  "sizeBytes" BIGINT NOT NULL CHECK ("sizeBytes" >= 0),
  "sha256" CHAR(64) NOT NULL,
  "entityType" VARCHAR(120) NOT NULL,
  "entityId" VARCHAR(120) NOT NULL,
  "uploadedById" UUID NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT,
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW()
);
CREATE INDEX "Attachment_entity_idx" ON "Attachment" ("entityType", "entityId", "createdAt");

CREATE TABLE "OutboxEvent" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "topic" VARCHAR(120) NOT NULL,
  "aggregateType" VARCHAR(120) NOT NULL,
  "aggregateId" VARCHAR(120) NOT NULL,
  "payload" JSONB NOT NULL,
  "status" "OutboxStatus" NOT NULL DEFAULT 'PENDING',
  "attempts" INTEGER NOT NULL DEFAULT 0 CHECK ("attempts" >= 0),
  "nextAttemptAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "lockedAt" TIMESTAMPTZ(6),
  "lockedBy" VARCHAR(120),
  "completedAt" TIMESTAMPTZ(6),
  "lastError" TEXT,
  "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW()
);
CREATE INDEX "OutboxEvent_status_nextAttempt_idx" ON "OutboxEvent" ("status", "nextAttemptAt");
CREATE INDEX "OutboxEvent_aggregate_idx" ON "OutboxEvent" ("aggregateType", "aggregateId");
